# general settings
name: train_DiNA13_SRx2_from_scratch
model_type: HATModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /home/kingerzee/data/cl/train/DF2K/HR/DF2K_HR_sub
    dataroot_lq: /home/kingerzee/data/cl/train/DF2K/LR/DF2K_X2_sub
    meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /home/kingerzee/data/cl/test/Set5/HR
    dataroot_lq: /home/kingerzee/data/cl/test/Set5/LR_bicubic/X2
    io_backend:
      type: disk

  val_2:
    name: Set14 
    type: PairedImageDataset
    dataroot_gt: /home/kingerzee/data/cl/test/Set14/HR
    dataroot_lq: /home/kingerzee/data/cl/test/Set14/BicLR/x2
    io_backend:
      type: disk

#  val_3:
#    name: Urban100
#    type: PairedImageDataset
#    dataroot_gt: /home/kingerzee/data/cl/test/urban100/HR/x2
#    dataroot_lq: /home/kingerzee/data/cl/test/urban100/BicLR/x2
#    io_backend:
#      type: disk


# network structures
network_g:
  type: HAT
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: /home/kingerzee/ChenLi/HAT-main/experiments/train_DiNA13_SRx2_from_scratch/models/net_g_990000.pth 
  strict_load_g: true
  resume_state:      /home/kingerzee/ChenLi/HAT-main/experiments/train_DiNA13_SRx2_from_scratch/training_states/990000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 370000, 450000, 475000, 550000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
